# -*-Makefile-*-

# Needed to make `"$@"` usable in recipes
set positional-arguments := true

debug:
  cargo build --debug

build:
  cargo build --release

quiet:
  cargo build --release --quiet

run *ARGS: quiet
  cargo run --release --quiet -- "$@"
